### ISSUE TITLE
The ChatWidgetLanguage in the chatConfig is not respected

### ISSUE THREAD

**Issue by pkaya89** [microsoft/omnichannel-chat-widget#213]
**Describe the bug**
The chat widget does not respect the language of the workstream and none of the UI text is translated. When using the widget script (iframe) the language is respected. Setting up the locale through props (webChatContainerProps.webChatProps) doesn't work either (tested with 'ru-RU', 'fr-FR' )

**To Reproduce**
1. Setup a workstream in a NON English language
2. The widget UI is not localised 

**Expected behavior**
The language used by the widget UI and its components should be the same as the one in the workstream.

**Screenshots**
<img width="768" alt="image" src="https://user-images.githubusercontent.com/35434040/218796534-bf4c98fd-7f11-4e32-89cb-be6afd6f82af.png">

The above screenshot shows that the msdyn_localeid is present in the ChatWidgetLanguage

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 110.0.5481.77

**Additional context**

**Comment by charliewang95** [comment]
The UI texts are placeholders only and are designed to not be localized. For non-English widgets, please update the corresponding controlProps.

The only exception for the above is WebChatContainer, whose built-in strings (send box placeholder, accessibility texts, etc.) will honor the locale retrieved from OC. For other strings within WebChat (timestamp, error banner texts, etc.), because we are using multiple webchat middlewares, you can modify the corresponding strings in this interface: https://github.com/microsoft/omnichannel-chat-widget/blob/edfd7feb97b96ad2438fc2183ccd005a69a4f43e/chat-widget/src/contexts/common/ILiveChatWidgetLocalizedTexts.ts#L1
